// Auto-generated from Notion knowledge sync -- do not edit manually
// Source: knowledge/notion/databases/pieces/ (items linked to each piece)
// Generated: 2026-03-26

export interface TemplatePieceItemSeed {
  piece_nom: string;
  item_nom: string;
  quantite_defaut: number;
}

export const templatePieceItems: TemplatePieceItemSeed[] = [
  // Balcon (12 items)
  { piece_nom: "Balcon", item_nom: "Rambarde / Garde-corps", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Store banne", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Pot(s) de fleur(s)", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Table extérieure", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Chaise(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Fauteuil(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Parasol", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Cendrier(s)", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Balcon", item_nom: "Prises électriques", quantite_defaut: 1 },

  // Buanderie / Cellier (21 items)
  { piece_nom: "Buanderie / Cellier", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Chauffe-eau / Ballon ECS", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Chaudière / Fuel", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Escabeau", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Étendoir / Tancarville", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Lave-linge", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Sèche-linge", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Fer à repasser", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Table à repasser", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Aspirateur", quantite_defaut: 1 },
  { piece_nom: "Buanderie / Cellier", item_nom: "Balai / Serpillière", quantite_defaut: 1 },

  // Bureau (20 items)
  { piece_nom: "Bureau", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Climatisation", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Chaise(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Bureau", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Étagère(s) de rangement", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Luminaire(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Bannette(s) / Caisson(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Multiprise(s)", quantite_defaut: 1 },
  { piece_nom: "Bureau", item_nom: "Rideaux", quantite_defaut: 1 },

  // Cabanon / Abri de jardin (6 items)
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Cabanon / Abri de jardin", item_nom: "Interrupteur(s)", quantite_defaut: 1 },

  // Cave (9 items)
  { piece_nom: "Cave", item_nom: "Chaudière / Fuel", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Cuve fuel / Citerne", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Cave", item_nom: "Interrupteur(s)", quantite_defaut: 1 },

  // Chambre (25 items)
  { piece_nom: "Chambre", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Climatisation", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Lit / Couchage", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Matelas", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Sommier", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Couette(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Oreiller(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Traversin(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Édredon(s) / Couvre-lit", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Chaise(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Fauteuil(s)", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Armoire", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Commode", quantite_defaut: 1 },
  { piece_nom: "Chambre", item_nom: "Bureau", quantite_defaut: 1 },

  // Couloir / Dégagement (12 items)
  { piece_nom: "Couloir / Dégagement", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Couloir / Dégagement", item_nom: "Cadre(s) / Décoration", quantite_defaut: 1 },

  // Cuisine (25 items)
  { piece_nom: "Cuisine", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Évier", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Plan de travail", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Crédence", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Éléments bas cuisine", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Éléments hauts cuisine", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Meuble sous évier", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Plan bar", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Poubelle encastrée", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Barre de crédence / Crémaillère", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Égouttoir", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Porte-couteaux / Bloc couteaux", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Chauffe-eau / Ballon ECS", quantite_defaut: 1 },
  { piece_nom: "Cuisine", item_nom: "Table", quantite_defaut: 1 },

  // Cuisine américaine (25 items)
  { piece_nom: "Cuisine américaine", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Évier", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Plan de travail", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Crédence", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Éléments bas cuisine", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Éléments hauts cuisine", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Meuble sous évier", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Plan bar", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Poubelle encastrée", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Barre de crédence / Crémaillère", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Égouttoir", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Porte-couteaux / Bloc couteaux", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Table", quantite_defaut: 1 },
  { piece_nom: "Cuisine américaine", item_nom: "Chaise(s)", quantite_defaut: 1 },

  // Dressing (13 items)
  { piece_nom: "Dressing", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Dressing / Penderie", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Luminaire(s)", quantite_defaut: 1 },
  { piece_nom: "Dressing", item_nom: "Miroir", quantite_defaut: 1 },

  // Entrée / Hall (17 items)
  { piece_nom: "Entrée / Hall", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Armoire", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Tapis", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Cadre(s) / Décoration", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Miroir", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Meuble à chaussures", quantite_defaut: 1 },
  { piece_nom: "Entrée / Hall", item_nom: "Porte-manteaux", quantite_defaut: 1 },

  // Équipements généraux (transverse) (12 items)
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Chauffe-eau / Ballon ECS", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Chaudière / Fuel", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Cuve fuel / Citerne", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Porte palière", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Interphone / Visiophone", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Sonnette", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Judas optique", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Boîte aux lettres", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Digicode / Badge", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Alarme", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Verrou(s)", quantite_defaut: 1 },
  { piece_nom: "Équipements généraux (transverse)", item_nom: "Détecteur de fumée", quantite_defaut: 1 },

  // Escalier (5 items)
  { piece_nom: "Escalier", item_nom: "Escalier intérieur", quantite_defaut: 1 },
  { piece_nom: "Escalier", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Escalier", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Escalier", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Escalier", item_nom: "Rambarde / Garde-corps", quantite_defaut: 1 },

  // Espaces verts (transverse) (6 items)
  { piece_nom: "Espaces verts (transverse)", item_nom: "Pelouse", quantite_defaut: 1 },
  { piece_nom: "Espaces verts (transverse)", item_nom: "Arbres / Arbustes", quantite_defaut: 1 },
  { piece_nom: "Espaces verts (transverse)", item_nom: "Massifs de fleurs / Plantations", quantite_defaut: 1 },
  { piece_nom: "Espaces verts (transverse)", item_nom: "Allées / Circulation extérieure", quantite_defaut: 1 },
  { piece_nom: "Espaces verts (transverse)", item_nom: "Tondeuse à gazon", quantite_defaut: 1 },
  { piece_nom: "Espaces verts (transverse)", item_nom: "Tuyau d'arrosage", quantite_defaut: 1 },

  // Extérieur / Bâti (transverse) (10 items)
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Rambarde / Garde-corps", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Store banne", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Portail / Portillon", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Clôture / Haie", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Porte de garage", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Toiture", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Façade", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Gouttières / Descentes EP", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Escalier extérieur", quantite_defaut: 1 },
  { piece_nom: "Extérieur / Bâti (transverse)", item_nom: "Porche / Véranda / Loggia", quantite_defaut: 1 },

  // Garage (10 items)
  { piece_nom: "Garage", item_nom: "Chaudière / Fuel", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Cuve fuel / Citerne", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Porte de garage", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Garage", item_nom: "Interrupteur(s)", quantite_defaut: 1 },

  // Grenier / Combles (7 items)
  { piece_nom: "Grenier / Combles", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Grenier / Combles", item_nom: "Interrupteur(s)", quantite_defaut: 1 },

  // Jardin / Cour (13 items)
  { piece_nom: "Jardin / Cour", item_nom: "Pelouse", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Arbres / Arbustes", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Massifs de fleurs / Plantations", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Allées / Circulation extérieure", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Table extérieure", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Chaise(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Fauteuil(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Parasol", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Bain de soleil / Chaise longue", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Banc extérieur", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Barbecue / Plancha", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Tondeuse à gazon", quantite_defaut: 1 },
  { piece_nom: "Jardin / Cour", item_nom: "Tuyau d'arrosage", quantite_defaut: 1 },

  // Loggia (5 items)
  { piece_nom: "Loggia", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Loggia", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Loggia", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Loggia", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Loggia", item_nom: "Rambarde / Garde-corps", quantite_defaut: 1 },

  // Mezzanine (11 items)
  { piece_nom: "Mezzanine", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Mezzanine", item_nom: "Éclairage(s)", quantite_defaut: 1 },

  // Palier (6 items)
  { piece_nom: "Palier", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Palier", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Palier", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Palier", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Palier", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Palier", item_nom: "Interrupteur(s)", quantite_defaut: 1 },

  // Parking / Box (2 items)
  { piece_nom: "Parking / Box", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Parking / Box", item_nom: "Éclairage(s)", quantite_defaut: 1 },

  // Salle à manger (20 items)
  { piece_nom: "Salle à manger", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Cheminée", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Table", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Chaise(s)", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Buffet / Vaisselier", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Rideaux", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Nappe(s) / Sets de table", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Serviette(s) de table", quantite_defaut: 1 },
  { piece_nom: "Salle à manger", item_nom: "Luminaire(s)", quantite_defaut: 1 },

  // Salle d'eau (23 items)
  { piece_nom: "Salle d'eau", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Lavabo / Vasque", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Douche", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Meuble sous lavabo", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Armoire à pharmacie / Miroir SDB", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Plan vasque", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Bidet", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Miroir", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Serviettes de bain", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Peignoir(s)", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Gant(s) de toilette", quantite_defaut: 1 },
  { piece_nom: "Salle d'eau", item_nom: "Brosse WC", quantite_defaut: 1 },

  // Salle de bain (25 items)
  { piece_nom: "Salle de bain", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Lavabo / Vasque", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Baignoire", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Douche", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Meuble sous lavabo", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Armoire à pharmacie / Miroir SDB", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Plan vasque", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Bidet", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "WC", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Chauffe-eau / Ballon ECS", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Miroir", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Serviettes de bain", quantite_defaut: 1 },
  { piece_nom: "Salle de bain", item_nom: "Peignoir(s)", quantite_defaut: 1 },

  // Salon / Séjour (25 items)
  { piece_nom: "Salon / Séjour", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Cheminée", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Climatisation", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Table", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Chaise(s)", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Canapé", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Fauteuil(s)", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Table basse", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Meuble TV / Multimédia", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Étagère(s) de rangement", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Luminaire(s)", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Tapis", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Cadre(s) / Décoration", quantite_defaut: 1 },
  { piece_nom: "Salon / Séjour", item_nom: "Convertible / Clic-clac / BZ", quantite_defaut: 1 },

  // Terrasse (15 items)
  { piece_nom: "Terrasse", item_nom: "Rambarde / Garde-corps", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Store banne", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Pot(s) de fleur(s)", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Table extérieure", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Chaise(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Fauteuil(s) de jardin", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Parasol", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Bain de soleil / Chaise longue", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Banc extérieur", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Barbecue / Plancha", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Cendrier(s)", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Terrasse", item_nom: "Prises électriques", quantite_defaut: 1 },

  // Véranda (9 items)
  { piece_nom: "Véranda", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Fenêtre", quantite_defaut: 1 },
  { piece_nom: "Véranda", item_nom: "Radiateur / Chauffage", quantite_defaut: 1 },

  // WC / Toilettes (14 items)
  { piece_nom: "WC / Toilettes", item_nom: "Sol", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Mur", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Plafond", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Plinthe", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Alaise / Moulure", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Porte", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Placards / Rangements", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Prises électriques", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Interrupteur(s)", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Éclairage(s)", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "WC", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Lave-mains", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Ventilation", quantite_defaut: 1 },
  { piece_nom: "WC / Toilettes", item_nom: "Brosse WC", quantite_defaut: 1 },

];
